server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:localhost:1521:XE
    username: C##OPENBANK
    password: OPENBANK

    jpa:
      generate-ddl: false
      show-sql: true
      database: oracle
      properties:
        hibernate.enable_lazy_load_no_trans: true
        hibernate:
          '[format_sql]': true
          use-new-id-generator-mappings: true
          temp:
            use_jdbc_metadata_defaults: false

