server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:XE
    username: C##NADABANK
    password: NADABANK

  # jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true

jwt:
  secret: OQPpcLHb31kqvS4hhz3xdjw+KfSbUiFffYnXsHsWcQ+0LUfP4gjk0kG+TNKxAE96D3Y9IN8PKqzOFdqrHavgcw==

OB_tokenRequestURL : https://testapi.openbanking.or.kr/oauth/2.0/token
OB_cardinfoReqURL : https://testapi.openbanking.or.kr/oauth/v2.0/cards
# 커밋할때 삭제하기
OB_client_key :
#

