### 거래내역조회
GET https://localhost:8080/api/accounts
Accept: */*


### 회원 등록
POST http://localhost:8080/api/member/signup
Content-Type: application/json
Accept: */* // 모든 파일 다 보냄
Access-Control-Allow-Origin: * // 모든 타입 다 보냄

{
  "memberId": "0000",
  "memberPassword": "0000"
}

### 로그인
POST http://localhost:8080/api/member/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "memberId": "0000",
  "memberPassword": "0000"
}

### OAuth 토큰 조회
GET https://testapi.openbanking.or.kr/oauth/2.0/authorize
Accept: */*

{
  "response_type": "code",
  "client_id": "ed0e3ff9a4574752b3bf3bbc390771ef",
  "redirect_uri": "http://localhost:3000",
  "scope": "login inquiry transfer",
  "state": 12345678901234567890123456789012,
  "auth_type": 0
}